config/routes.rb
# frozen_string_literal: true

GoodJob::Engine.routes.draw do
  root to: redirect(path: 'jobs')

  resources :jobs, only: %i[index show destroy] do
    collection do
      get :mass_update, to: redirect(path: 'jobs')
      put :mass_update
    end

    member do
      put :discard
      put :force_discard
      put :reschedule
      put :retry
    end
  end
  get 'jobs/metrics/primary_nav', to: 'metrics#primary_nav', as: :metrics_primary_nav
  get 'jobs/metrics/job_status', to: 'metrics#job_status', as: :metrics_job_status

  resources :batches, only: %i[index show]

  resources :cron_entries, only: %i[index show], param: :cron_key do
    member do
      post :enqueue
      put :enable
      put :disable
    end
  end

  resources :processes, only: %i[index]

  scope :frontend, controller: :frontends do
    get "modules/:name", action: :module, as: :frontend_module, constraints: { format: 'js' }
    get "static/:name", action: :static, as: :frontend_static, constraints: { format: %w[css js] }
  end
end

app/models/concerns/good_job/advisory_lockable.rb
# frozen_string_literal: true

module GoodJob
  #
  # Adds Postgres advisory locking capabilities to an ActiveRecord record.
  # For details on advisory locks, see the Postgres documentation:
  # - {https://www.postgresql.org/docs/current/explicit-locking.html#ADVISORY-LOCKS Advisory Locks Overview}
  # - {https://www.postgresql.org/docs/current/functions-admin.html#FUNCTIONS-ADVISORY-LOCKS Advisory Locks Functions}
  #
  # @example Add this concern to a +MyRecord+ class:
  #   class MyRecord < ActiveRecord::Base
  #     include Lockable
  #
  #     def my_method
  #       ...
  #     end
  #   end
  #
  module AdvisoryLockable
    extend ActiveSupport::Concern

    # Indicates an advisory lock is already held on a record by another
    # database session.
    RecordAlreadyAdvisoryLockedError = Class.new(StandardError)

    included do
      # Default column to be used when creating Advisory Locks
      class_attribute :advisory_lockable_column, instance_accessor: false, default: nil

      # Default Postgres function to be used for Advisory Locks
      class_attribute :advisory_lockable_function, default: "pg_try_advisory_lock"

      # Attempt to acquire an advisory lock on the selected records and
      # return only those records for which a lock could be acquired.
      # @!method advisory_lock(column: _advisory_lockable_column, function: advisory_lockable_function)
      # @!scope class
      # @param column [String, Symbol] column values to Advisory Lock against
      # @param function [String, Symbol]  Postgres Advisory Lock function name to use
      # @return [ActiveRecord::Relation]
      #   A relation selecting only the records that were locked.
      scope :advisory_lock, (lambda do |column: _advisory_lockable_column, function: advisory_lockable_function, select_limit: nil|
        original_query = self

        cte_table = Arel::Table.new(:rows)
        cte_query = original_query.select(primary_key, column).except(:limit)
        cte_query = cte_query.limit(select_limit) if select_limit
        cte_type = supports_cte_materialization_specifiers? ? :MATERIALIZED : :""
        composed_cte = Arel::Nodes::As.new(cte_table, Arel::Nodes::UnaryOperation.new(cte_type, cte_query.arel))

        lock_condition = "#{function}(('x' || substr(md5(#{connection.quote(table_name)} || '-' || #{connection.quote_table_name(cte_table.name)}.#{connection.quote_column_name(column)}::text), 1, 16))::bit(64)::bigint)"
        query = cte_table.project(cte_table[:id])
                         .with(composed_cte)
                         .where(defined?(Arel::Nodes::BoundSqlLiteral) ? Arel::Nodes::BoundSqlLiteral.new(lock_condition, [], {}) : Arel::Nodes::SqlLiteral.new(lock_condition))

        limit = original_query.arel.ast.limit
        query.limit = limit.value if limit.present?

        # Arel.sql and the IN clause prevent this from being preparable
        # That's why this is manually composed of BoundSqlLiteral's and an InfixOperation
        # to sidestep anywhere in Arel where the `collector.preparable = false` is set
        unscoped.where(Arel::Nodes::InfixOperation.new("IN", arel_table[primary_key], query)).merge(original_query.only(:order))
      end)

      # Joins the current query with Postgres's +pg_locks+ table (it provides
      # data about existing locks) such that each row in the main query joins
      # to all the advisory locks associated with that row.
      #
      # For details on +pg_locks+, see
      # {https://www.postgresql.org/docs/current/view-pg-locks.html}.
      # @!method joins_advisory_locks(column: _advisory_lockable_column)
      # @!scope class
      # @param column [String, Symbol] column values to Advisory Lock against
      # @return [ActiveRecord::Relation]
      # @example Get the records that have a session awaiting a lock:
      #   MyLockableRecord.joins_advisory_locks.where("pg_locks.granted = ?", false)
      scope :joins_advisory_locks, (lambda do |column: _advisory_lockable_column|
        joins(<<~SQL.squish)
          LEFT JOIN pg_locks ON pg_locks.locktype = 'advisory'
            AND pg_locks.objsubid = 1
            AND pg_locks.classid = ('x' || substr(md5(#{connection.quote(table_name)} || '-' || #{quoted_table_name}.#{connection.quote_column_name(column)}::text), 1, 16))::bit(32)::int
            AND pg_locks.objid = (('x' || substr(md5(#{connection.quote(table_name)} || '-' || #{quoted_table_name}.#{connection.quote_column_name(column)}::text), 1, 16))::bit(64) << 32)::bit(32)::int
        SQL
      end)

      # Joins the current query with Postgres's +pg_locks+ table AND SELECTs the resulting columns
      # @!method joins_advisory_locks(column: _advisory_lockable_column)
      # @!scope class
      # @param column [String, Symbol] column values to Advisory Lock against
      # @return [ActiveRecord::Relation]
      scope :includes_advisory_locks, (lambda do |column: _advisory_lockable_column|
        owns_advisory_lock_sql = "#{connection.quote_table_name('pg_locks')}.#{connection.quote_column_name('pid')} = pg_backend_pid() AS owns_advisory_lock"
        joins_advisory_locks(column: column).select("#{quoted_table_name}.*, #{connection.quote_table_name('pg_locks')}.locktype, #{owns_advisory_lock_sql}")
      end)

      # Find records that do not have an advisory lock on them.
      # @!method advisory_unlocked(column: _advisory_lockable_column)
      # @!scope class
      # @param column [String, Symbol] column values to Advisory Lock against
      # @return [ActiveRecord::Relation]
      scope :advisory_unlocked, ->(column: _advisory_lockable_column) { joins_advisory_locks(column: column).where(pg_locks: { locktype: nil }) }

      # Find records that have an advisory lock on them.
      # @!method advisory_locked(column: _advisory_lockable_column)
      # @!scope class
      # @param column [String, Symbol] column values to Advisory Lock against
      # @return [ActiveRecord::Relation]
      scope :advisory_locked, ->(column: _advisory_lockable_column) { joins_advisory_locks(column: column).where.not(pg_locks: { locktype: nil }) }

      # Find records with advisory locks owned by the current Postgres
      # session/connection.
      # @!method advisory_locked(column: _advisory_lockable_column)
      # @!scope class
      # @param column [String, Symbol] column values to Advisory Lock against
      # @return [ActiveRecord::Relation]
      scope :owns_advisory_locked, ->(column: _advisory_lockable_column) { joins_advisory_locks(column: column).where('"pg_locks"."pid" = pg_backend_pid()') }

      # Whether an advisory lock should be acquired in the same transaction
      # that created the record.
      #
      # This helps prevent another thread or database session from acquiring a
      # lock on the record between the time you create it and the time you
      # request a lock, since other sessions will not be able to see the new
      # record until the transaction that creates it is completed (at which
      # point you have already acquired the lock).
      #
      # @example
      #   record = MyLockableRecord.create(create_with_advisory_lock: true)
      #   record.advisory_locked?
      #   => true
      #
      # @return [Boolean]
      attr_accessor :create_with_advisory_lock

      after_create lambda {
        advisory_lock || begin
          errors.add(self.class.advisory_lockable_column, "Failed to acquire advisory lock: #{lockable_key}")
          raise ActiveRecord::RecordInvalid # do not reference the record because it can cause I18n missing translation error
        end
      }, if: :create_with_advisory_lock
    end

    class_methods do
      # Acquires an advisory lock on the selected record(s) and safely releases
      # it after the passed block is completed. The block will be passed an
      # array of the locked records as its first argument.
      #
      # Note that this will not block and wait for locks to be acquired.
      # Instead, it will acquire a lock on all the selected records that it
      # can (as in {Lockable.advisory_lock}) and only pass those that could be
      # locked to the block.
      #
      # If the Active Record Relation has WHERE conditions that have the potential
      # to be updated/changed elsewhere, be sure to verify the conditions are still
      # satisfied, or check the lock status, as an unlocked and out-of-date record could be returned.
      #
      # @param column [String, Symbol]  name of advisory lock or unlock function
      # @param function [String, Symbol] Postgres Advisory Lock function name to use
      # @param unlock_session [Boolean] Whether to unlock all advisory locks in the session afterwards
      # @yield [Array<Lockable>] the records that were successfully locked.
      # @return [Object] the result of the block.
      #
      # @example Work on the first two +MyLockableRecord+ objects that could be locked:
      #   MyLockableRecord.order(created_at: :asc).limit(2).with_advisory_lock do |record|
      #     do_something_with record
      #   end
      def with_advisory_lock(column: _advisory_lockable_column, function: advisory_lockable_function, unlock_session: false, select_limit: nil)
        raise ArgumentError, "Must provide a block" unless block_given?

        records = advisory_lock(column: column, function: function, select_limit: select_limit).to_a

        begin
          unscoped { yield(records) }
        ensure
          if unlock_session
            advisory_unlock_session
          else
            records.each do |record|
              record.advisory_unlock(key: record.lockable_column_key(column: column), function: advisory_unlockable_function(function))
            end
          end
        end
      end

      # Acquires an advisory lock on this record if it is not already locked by
      # another database session. Be careful to ensure you release the lock when
      # you are done with {#advisory_unlock_key} to release all remaining locks.

app/models/concerns/good_job/error_events.rb
# frozen_string_literal: true

module GoodJob
  # Shared methods for filtering Execution/Job records from the +good_jobs+ table.
  module ErrorEvents
    extend ActiveSupport::Concern

    ERROR_EVENTS = [
      ERROR_EVENT_INTERRUPTED = 'interrupted',
      ERROR_EVENT_UNHANDLED = 'unhandled',
      ERROR_EVENT_HANDLED = 'handled',
      ERROR_EVENT_RETRIED = 'retried',
      ERROR_EVENT_RETRY_STOPPED = 'retry_stopped',
      ERROR_EVENT_DISCARDED = 'discarded',
    ].freeze

    ERROR_EVENT_ENUMS = {
      ERROR_EVENT_INTERRUPTED => 0,
      ERROR_EVENT_UNHANDLED => 1,
      ERROR_EVENT_HANDLED => 2,
      ERROR_EVENT_RETRIED => 3,
      ERROR_EVENT_RETRY_STOPPED => 4,
      ERROR_EVENT_DISCARDED => 5,
    }.freeze

    # TODO: GoodJob v4 can make this an `enum` once migrations are guaranteed.
    def error_event
      return unless self.class.columns_hash['error_event']

      enum = super
      return unless enum

      ERROR_EVENT_ENUMS.key(enum)
    end

    def error_event=(event)
      return unless self.class.columns_hash['error_event']

      enum = ERROR_EVENT_ENUMS[event]
      raise(ArgumentError, "Invalid error_event: #{event}") if event && !enum

      super(enum)
    end
  end
end

app/models/concerns/good_job/filterable.rb
# frozen_string_literal: true

module GoodJob
  # Shared methods for filtering Execution/Job records from the +good_jobs+ table.
  module Filterable
    extend ActiveSupport::Concern

    included do
      # Get records in display order with optional keyset pagination.
      # @!method display_all(after_scheduled_at: nil, after_id: nil)
      # @!scope class
      # @param after_scheduled_at [DateTime, String, nil]
      #   Display records scheduled after this time for keyset pagination
      # @param after_id [Numeric, String, nil]
      #   Display records after this ID for keyset pagination
      # @return [ActiveRecord::Relation]
      scope :display_all, (lambda do |after_scheduled_at: nil, after_id: nil|
        query = order(Arel.sql('COALESCE(scheduled_at, created_at) DESC, id DESC'))
        if after_scheduled_at.present? && after_id.present?
          query = query.where Arel::Nodes::Grouping.new([coalesce_scheduled_at_created_at, arel_table["id"]]).lt(Arel::Nodes::Grouping.new([bind_value('coalesce', after_scheduled_at, ActiveRecord::Type::DateTime), bind_value('id', after_id, ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Uuid)]))
        elsif after_scheduled_at.present?
          query = query.where coalesce_scheduled_at_created_at.lt(bind_value('coalesce', after_scheduled_at, ActiveRecord::Type::DateTime))
        end
        query
      end)

      # Search records by text query.
      # @!method search_text(query)
      # @!scope class
      # @param query [String]
      #   Search Query
      # @return [ActiveRecord::Relation]
      scope :search_text, (lambda do |query|
        query = query.to_s.strip
        next if query.blank?

        # TODO: turn this into proper bind parameters in Arel
        tsvector = "(to_tsvector('english', id::text) || to_tsvector('english', COALESCE(active_job_id::text, '')) || to_tsvector('english', serialized_params) || to_tsvector('english', COALESCE(error, ''))#{" || to_tsvector('english', COALESCE(array_to_string(labels, ' '), ''))" if labels_migrated?})"
        to_tsquery_function = database_supports_websearch_to_tsquery? ? 'websearch_to_tsquery' : 'plainto_tsquery'
        where("#{tsvector} @@ #{to_tsquery_function}(?)", query)
          .order(sanitize_sql_for_order([Arel.sql("ts_rank(#{tsvector}, #{to_tsquery_function}(?))"), query]) => 'DESC')
      end)
    end

    class_methods do
      def database_supports_websearch_to_tsquery?
        return @_database_supports_websearch_to_tsquery if defined?(@_database_supports_websearch_to_tsquery)

        @_database_supports_websearch_to_tsquery = connection.postgresql_version >= 110000
      end
    end
  end
end

app/models/good_job/active_record_parent_class.rb
# frozen_string_literal: true

module GoodJob
  ActiveRecordParentClass = if GoodJob.active_record_parent_class
                              Object.const_get(GoodJob.active_record_parent_class)
                            else
                              ActiveRecord::Base
                            end
end

app/controllers/good_job/application_controller.rb
# frozen_string_literal: true

module GoodJob
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    around_action :use_good_job_locale

    content_security_policy do |policy|
      policy.default_src(:none) if policy.default_src(*policy.default_src).blank?
      policy.connect_src(:self) if policy.connect_src(*policy.connect_src).blank?
      policy.base_uri(:none) if policy.base_uri(*policy.base_uri).blank?
      policy.font_src(:self) if policy.font_src(*policy.font_src).blank?
      policy.img_src(:self, :data) if policy.img_src(*policy.img_src).blank?
      policy.object_src(:none) if policy.object_src(*policy.object_src).blank?
      policy.script_src(:self) if policy.script_src(*policy.script_src).blank?
      policy.style_src(:self) if policy.style_src(*policy.style_src).blank?
      policy.form_action(:self) if policy.form_action(*policy.form_action).blank?
      policy.frame_ancestors(:none) if policy.frame_ancestors(*policy.frame_ancestors).blank?
    end

    before_action do
      next if request.content_security_policy_nonce_generator

      request.content_security_policy_nonce_generator = ->(_request) { SecureRandom.base64(16) }
    end

    private

    def default_url_options(options = {})
      { locale: I18n.locale }.merge(options)
    end

    def use_good_job_locale(&action)
      @original_i18n_config = I18n.config
      I18n.config = ::GoodJob::I18nConfig.new
      I18n.with_locale(current_locale, &action)
    ensure
      I18n.config = @original_i18n_config
      @original_i18n_config = nil
    end

    def use_original_locale
      prev_config = I18n.config
      I18n.config = @original_i18n_config if @original_i18n_config
      yield
    ensure
      I18n.config = prev_config
    end

    def current_locale
      if request.GET['locale']
        request.GET['locale']
      elsif params[:locale]
        params[:locale]
      else
        I18n.default_locale
      end
    end

    ActiveSupport.run_load_hooks(:good_job_application_controller, self)
  end
end

app/controllers/good_job/batches_controller.rb
# frozen_string_literal: true

module GoodJob
  class BatchesController < GoodJob::ApplicationController
    def index
      @filter = BatchesFilter.new(params)
    end

    def show
      @batch = GoodJob::BatchRecord.find(params[:id])
    end
  end
end

app/views/good_job/cron_entries/index.html.erb
<div class="border-bottom">
  <h2 class="pt-3 pb-2"><%= t ".title" %></h2>
</div>

<div class="card my-3">
  <div class="list-group list-group-flush text-nowrap" role="table">
    <header class="list-group-item body-secondary">
      <div class="row small text-muted text-uppercase align-items-center">
        <div class="col-12 col-lg-2"></div>
        <div class="col-6 col-lg-2 d-none d-lg-block"><%= t "good_job.models.cron.class" %></div>
        <div class="col-6 col-lg-2 d-none d-lg-block"><%= t "good_job.models.cron.schedule" %></div>
        <div class="col-6 col-lg-2 d-none d-lg-block"><%= t "good_job.models.cron.next_scheduled" %></div>
        <div class="col-6 col-lg-2 d-none d-lg-block"><%= t "good_job.models.cron.last_run" %></div>
        <div class="col text-end">
          <%= tag.button type: "button", class: "btn btn-sm text-muted", role: "button",
                         data: { bs_toggle: "collapse", bs_target: ".cron-entry-properties" },
                         aria: { expanded: false, controls: @cron_entries.map { |cron_entry| "##{dom_id(cron_entry, 'properties')}" }.join(" ") } do %>
            <%= render_icon "info" %>
            <span class="visually-hidden"><%= t "good_job.actions.inspect" %></span>
          <% end %>
        </div>
      </div>
    </header>
    <% @cron_entries.each do |cron_entry| %>
      <div id="<%= dom_id(cron_entry) %>" class="list-group-item py-3" role="row">
        <div class="row align-items-center">
          <div class="col-12 col-lg-2">
            <div class="small font-monospace"><%= cron_entry.key %></div>
            <div class="small text-muted text-wrap"><%= cron_entry.description %></div>
          </div>
          <div class="col-12 col-lg-2 text-wrap"><%= tag.span tag.code(cron_entry.job_class), class: "fs-5 mb-0" %></div>
          <div class="col-6 col-lg-2 text-wrap">
            <div class="d-lg-none small text-muted mt-1"><%= t "good_job.models.cron.schedule" %></div>
            <span class="font-monospace fw-bold"><%= cron_entry.display_schedule %></span>
          </div>
          <div class="col-6 col-lg-2 text-wrap small">
            <div class="d-lg-none small text-muted mt-1"><%= t "good_job.models.cron.next_scheduled" %></div>
            <%= relative_time cron_entry.next_at %>
          </div>
          <div class="col-6 col-lg-2 text-wrap small">
            <% if cron_entry.last_job.present? %>
              <div class="d-lg-none small text-muted mt-1"><%= t "good_job.models.cron.last_run" %></div>
              <%= link_to relative_time(cron_entry.last_job_at), cron_entry_path(cron_entry), title: "Job #{cron_entry.last_job.id}" %>
            <% end %>
          </div>
          <div class="col d-flex gap-3 justify-content-end">
            <%= button_to enqueue_cron_entry_path(cron_entry), method: :post, class: "btn btn-sm btn-outline-primary", form_class: "d-inline-block", aria: { label: t("good_job.cron_entries.actions.enqueue") }, title: t("good_job.cron_entries.actions.enqueue"), data: { confirm: t("good_job.cron_entries.actions.confirm_enqueue") } do %>
              <%= render_icon "skip_forward" %>
            <% end %>

            <% if cron_entry.enabled? %>
              <%= button_to disable_cron_entry_path(cron_entry), method: :put, class: "btn btn-sm btn-outline-primary", form_class: "d-inline-block", aria: { label: t("good_job.cron_entries.actions.disable") }, title: t("good_job.cron_entries.actions.disable"), data: { confirm: t("good_job.cron_entries.actions.confirm_disable") } do %>
                <%= render_icon "pause" %>
              <% end %>
            <% else %>
              <%= button_to enable_cron_entry_path(cron_entry), method: :put, class: "btn btn-sm btn-outline-primary", form_class: "d-inline-block", aria: { label: t("good_job.cron_entries.actions.enable") }, title: t("good_job.cron_entries.actions.enable"), data: { confirm: t("good_job.cron_entries.actions.confirm_enable") } do %>
                <%= render_icon "play" %>
              <% end %>
            <% end %>

            <%= tag.button type: "button", class: "btn btn-sm text-muted", role: "button",
                           title: t("good_job.actions.inspect"),
                           data: { bs_toggle: "collapse", bs_target: "##{dom_id(cron_entry, 'properties')}" },
                           aria: { expanded: false, controls: dom_id(cron_entry, "properties") } do %>
              <%= render_icon "info" %>
              <span class="visually-hidden"><%= t "good_job.actions.inspect" %></span>
            <% end %>
          </div>
        </div>
      </div>
      <%= tag.div id: dom_id(cron_entry, 'properties'), class: "collapse cron-entry-properties list-group-item collapse small bg-dark text-secondary" do %>
        <%= tag.pre JSON.pretty_generate(cron_entry.display_properties) %>
      <% end %>
    <% end %>
    <% if @cron_entries.empty? %>
      <div class="list-group-item py-4 text-center text-muted">
        <%= t ".no_cron_schedules_found" %>
      </div>
    <% end %>
  </div>
</div>

app/views/good_job/cron_entries/show.html.erb
<% title = capture do %>
  <%= t ".cron_entry_key" %>: <code><%= @cron_entry.id %></code>
<% end %>

<%= render 'good_job/shared/filter', title: title, filter: @jobs_filter %>
<%= render 'good_job/jobs/table', jobs: @jobs_filter.records, filter: @jobs_filter %>