config/routes.rb
# frozen_string_literal: true

GoodJob::Engine.routes.draw do
  root to: redirect(path: 'jobs')

  resources :jobs, only: %i[index show destroy] do
    collection do
      get :mass_update, to: redirect(path: 'jobs')
      put :mass_update
    end

    member do
      put :discard
      put :force_discard
      put :reschedule
      put :retry
    end
  end
  get 'jobs/metrics/primary_nav', to: 'metrics#primary_nav', as: :metrics_primary_nav
  get 'jobs/metrics/job_status', to: 'metrics#job_status', as: :metrics_job_status

  resources :batches, only: %i[index show]

  resources :cron_entries, only: %i[index show], param: :cron_key do
    member do
      post :enqueue
      put :enable
      put :disable
    end
  end

  resources :processes, only: %i[index]

  scope :frontend, controller: :frontends do
    get "modules/:name", action: :module, as: :frontend_module, constraints: { format: 'js' }
    get "static/:name", action: :static, as: :frontend_static, constraints: { format: %w[css js] }
  end
end

app/models/concerns/good_job/error_events.rb
# frozen_string_literal: true

module GoodJob
  # Shared methods for filtering Execution/Job records from the +good_jobs+ table.
  module ErrorEvents
    extend ActiveSupport::Concern

    ERROR_EVENTS = [
      ERROR_EVENT_INTERRUPTED = 'interrupted',
      ERROR_EVENT_UNHANDLED = 'unhandled',
      ERROR_EVENT_HANDLED = 'handled',
      ERROR_EVENT_RETRIED = 'retried',
      ERROR_EVENT_RETRY_STOPPED = 'retry_stopped',
      ERROR_EVENT_DISCARDED = 'discarded',
    ].freeze

    ERROR_EVENT_ENUMS = {
      ERROR_EVENT_INTERRUPTED => 0,
      ERROR_EVENT_UNHANDLED => 1,
      ERROR_EVENT_HANDLED => 2,
      ERROR_EVENT_RETRIED => 3,
      ERROR_EVENT_RETRY_STOPPED => 4,
      ERROR_EVENT_DISCARDED => 5,
    }.freeze

    # TODO: GoodJob v4 can make this an `enum` once migrations are guaranteed.
    def error_event
      return unless self.class.columns_hash['error_event']

      enum = super
      return unless enum

      ERROR_EVENT_ENUMS.key(enum)
    end

    def error_event=(event)
      return unless self.class.columns_hash['error_event']

      enum = ERROR_EVENT_ENUMS[event]
      raise(ArgumentError, "Invalid error_event: #{event}") if event && !enum

      super(enum)
    end
  end
end

app/models/concerns/good_job/filterable.rb
# frozen_string_literal: true

module GoodJob
  # Shared methods for filtering Execution/Job records from the +good_jobs+ table.
  module Filterable
    extend ActiveSupport::Concern

    included do
      # Get records in display order with optional keyset pagination.
      # @!method display_all(after_scheduled_at: nil, after_id: nil)
      # @!scope class
      # @param after_scheduled_at [DateTime, String, nil]
      #   Display records scheduled after this time for keyset pagination
      # @param after_id [Numeric, String, nil]
      #   Display records after this ID for keyset pagination
      # @return [ActiveRecord::Relation]
      scope :display_all, (lambda do |after_scheduled_at: nil, after_id: nil|
        query = order(Arel.sql('COALESCE(scheduled_at, created_at) DESC, id DESC'))
        if after_scheduled_at.present? && after_id.present?
          query = query.where Arel::Nodes::Grouping.new([coalesce_scheduled_at_created_at, arel_table["id"]]).lt(Arel::Nodes::Grouping.new([bind_value('coalesce', after_scheduled_at, ActiveRecord::Type::DateTime), bind_value('id', after_id, ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Uuid)]))
        elsif after_scheduled_at.present?
          query = query.where coalesce_scheduled_at_created_at.lt(bind_value('coalesce', after_scheduled_at, ActiveRecord::Type::DateTime))
        end
        query
      end)

      # Search records by text query.
      # @!method search_text(query)
      # @!scope class
      # @param query [String]
      #   Search Query
      # @return [ActiveRecord::Relation]
      scope :search_text, (lambda do |query|
        query = query.to_s.strip
        next if query.blank?

        # TODO: turn this into proper bind parameters in Arel
        tsvector = "(to_tsvector('english', id::text) || to_tsvector('english', COALESCE(active_job_id::text, '')) || to_tsvector('english', serialized_params) || to_tsvector('english', COALESCE(error, ''))#{" || to_tsvector('english', COALESCE(array_to_string(labels, ' '), ''))" if labels_migrated?})"
        to_tsquery_function = database_supports_websearch_to_tsquery? ? 'websearch_to_tsquery' : 'plainto_tsquery'
        where("#{tsvector} @@ #{to_tsquery_function}(?)", query)
          .order(sanitize_sql_for_order([Arel.sql("ts_rank(#{tsvector}, #{to_tsquery_function}(?))"), query]) => 'DESC')
      end)
    end

    class_methods do
      def database_supports_websearch_to_tsquery?
        return @_database_supports_websearch_to_tsquery if defined?(@_database_supports_websearch_to_tsquery)

        @_database_supports_websearch_to_tsquery = connection.postgresql_version >= 110000
      end
    end
  end
end

app/models/concerns/good_job/reportable.rb
# frozen_string_literal: true

module GoodJob
  module Reportable
    # There are 3 buckets of non-overlapping statuses:
    #   1. The job will be executed
    #     - queued: The job will execute immediately when an execution thread becomes available.
    #     - scheduled: The job is scheduled to execute in the future.
    #     - retried: The job previously errored on execution and will be re-executed in the future.
    #   2. The job is being executed
    #     - running: the job is actively being executed by an execution thread
    #   3. The job has finished
    #     - succeeded: The job executed successfully
    #     - discarded: The job previously errored on execution and will not be re-executed in the future.
    #
    # @return [Symbol]
    def status
      if finished_at.present?
        if error.present? && retried_good_job_id.present?
          :retried
        elsif error.present? && retried_good_job_id.nil?
          :discarded
        else
          :succeeded
        end
      elsif (scheduled_at || created_at) > DateTime.current
        if serialized_params.fetch('executions', 0) > 1
          :retried
        else
          :scheduled
        end
      elsif running?
        :running
      else
        :queued
      end
    end

    # The last relevant timestamp for this execution
    def last_status_at
      finished_at || performed_at || scheduled_at || created_at
    end
  end
end

app/models/good_job/active_record_parent_class.rb
# frozen_string_literal: true

module GoodJob
  ActiveRecordParentClass = if GoodJob.active_record_parent_class
                              Object.const_get(GoodJob.active_record_parent_class)
                            else
                              ActiveRecord::Base
                            end
end

app/models/good_job/base_execution.rb
# frozen_string_literal: true

module GoodJob
  # Active Record model to share behavior between {Job} and {Execution} models
  # which both read out of the same table.
  class BaseExecution < BaseRecord
    include AdvisoryLockable
    include ErrorEvents
    include Filterable
    include Reportable

    self.table_name = 'good_jobs'

    # With a given class name
    # @!method job_class(name)
    # @!scope class
    # @param name [String] Execution class name
    # @return [ActiveRecord::Relation]
    scope :job_class, ->(name) { where(params_job_class.eq(name)) }

    class << self
      def json_string(json, attr)
        Arel::Nodes::Grouping.new(Arel::Nodes::InfixOperation.new('->>', json, Arel::Nodes.build_quoted(attr)))
      end

      def params_job_class
        json_string(arel_table['serialized_params'], 'job_class')
      end

      def params_execution_count
        Arel::Nodes::InfixOperation.new(
          '::',
          json_string(arel_table['serialized_params'], 'executions'),
          Arel.sql('integer')
        )
      end

      def coalesce_scheduled_at_created_at
        arel_table.coalesce(arel_table['scheduled_at'], arel_table['created_at'])
      end

      def discrete_support?
        GoodJob::DiscreteExecution.migrated?
      end

      def error_event_migrated?
        return true if columns_hash["error_event"].present?

        migration_pending_warning!
        false
      end

      def cron_indices_migrated?
        return true if connection.index_name_exists?(:good_jobs, :index_good_jobs_on_cron_key_and_created_at_cond)

        migration_pending_warning!
        false
      end

      def labels_migrated?
        return true if columns_hash["labels"].present?

        migration_pending_warning!
        false
      end

      def labels_indices_migrated?
        return true if connection.index_name_exists?(:good_jobs, :index_good_jobs_on_labels)

        migration_pending_warning!
        false
      end

      def active_job_id_index_removal_migrated?
        return true unless connection.index_name_exists?(:good_jobs, :index_good_jobs_on_active_job_id)

        migration_pending_warning!
        false
      end

      def candidate_lookup_index_migrated?
        return true if connection.index_name_exists?(:good_jobs, :index_good_job_jobs_for_candidate_lookup)

        migration_pending_warning!
        false
      end

      def process_lock_migrated?
        return true if connection.index_name_exists?(:good_job_executions, :index_good_job_executions_on_process_id_and_created_at)

        migration_pending_warning!
        false
      end
    end

    # The ActiveJob job class, as a string
    # @return [String]
    def job_class
      discrete? ? attributes['job_class'] : serialized_params['job_class']
    end

    def discrete?
      self.class.discrete_support? && is_discrete?
    end

    # Build an ActiveJob instance and deserialize the arguments, using `#active_job_data`.
    #
    # @param ignore_deserialization_errors [Boolean]
    #   Whether to ignore ActiveJob::DeserializationError and NameError when deserializing the arguments.
    #   This is most useful if you aren't planning to use the arguments directly.
    def active_job(ignore_deserialization_errors: false)
      ActiveJob::Base.deserialize(active_job_data).tap do |aj|
        aj.send(:deserialize_arguments_if_needed)
      rescue ActiveJob::DeserializationError
        raise unless ignore_deserialization_errors
      end
    rescue NameError
      raise unless ignore_deserialization_errors
    end

    private

    def active_job_data
      serialized_params.deep_dup
                       .tap do |job_data|
        job_data["provider_job_id"] = id
        job_data["good_job_concurrency_key"] = concurrency_key if concurrency_key
        job_data["good_job_labels"] = Array(labels) if self.class.labels_migrated? && labels.present?
      end
    end
  end
end

app/models/good_job/batch_record.rb
# frozen_string_literal: true

require 'active_job/arguments'

module GoodJob
  class BatchRecord < BaseRecord
    include AdvisoryLockable

    self.table_name = 'good_job_batches'
    self.implicit_order_column = 'created_at'

    has_many :jobs, class_name: 'GoodJob::Job', inverse_of: :batch, foreign_key: :batch_id, dependent: nil
    has_many :executions, class_name: 'GoodJob::Execution', foreign_key: :batch_id, inverse_of: :batch, dependent: nil
    has_many :callback_jobs, class_name: 'GoodJob::Job', foreign_key: :batch_callback_id, dependent: nil # rubocop:disable Rails/InverseOf

    scope :finished, -> { where.not(finished_at: nil) }
    scope :discarded, -> { where.not(discarded_at: nil) }
    scope :not_discarded, -> { where(discarded_at: nil) }
    scope :succeeded, -> { finished.not_discarded }

    scope :finished_before, ->(timestamp) { where(arel_table['finished_at'].lteq(bind_value('finished_at', timestamp, ActiveRecord::Type::DateTime))) }

    alias_attribute :enqueued?, :enqueued_at
    alias_attribute :discarded?, :discarded_at
    alias_attribute :finished?, :finished_at

    scope :display_all, (lambda do |after_created_at: nil, after_id: nil|
      query = order(created_at: :desc, id: :desc)
      if after_created_at.present? && after_id.present?
        query = if Gem::Version.new(Rails.version) < Gem::Version.new('7.0.0.a') || Concurrent.on_jruby?
                  query.where(Arel.sql('(created_at, id) < (:after_created_at, :after_id)'), after_created_at: after_created_at, after_id: after_id)
                else
                  query.where Arel::Nodes::Grouping.new([arel_table["created_at"], arel_table["id"]]).lt(Arel::Nodes::Grouping.new([bind_value('created_at', after_created_at, ActiveRecord::Type::DateTime), bind_value('id', after_id, ActiveRecord::Type::String)]))
                end
      elsif after_created_at.present?
        query = query.where arel_table["created_at"].lt(bind_value('created_at', after_created_at, ActiveRecord::Type::DateTime))
      end
      query
    end)

    # Whether the batch has finished and no jobs were discarded
    # @return [Boolean]
    def succeeded?
      !discarded? && finished?
    end

    def to_batch
      Batch.new(_record: self)
    end

    def display_attributes
      attributes.except('serialized_properties').merge(properties: properties)
    end

    def _continue_discard_or_finish(execution = nil, lock: true)
      execution_discarded = execution && execution.error.present? && execution.finished_at && execution.retried_good_job_id.nil?
      take_advisory_lock(lock) do
        Batch.within_thread(batch_id: nil, batch_callback_id: id) do
          reload
          if execution_discarded && !discarded_at
            update(discarded_at: Time.current)
            on_discard.constantize.set(priority: callback_priority, queue: callback_queue_name).perform_later(to_batch, { event: :discard }) if on_discard.present?
          end

          if enqueued_at && !finished_at && jobs.where(finished_at: nil).count.zero?
            update(finished_at: Time.current)
            on_success.constantize.set(priority: callback_priority, queue: callback_queue_name).perform_later(to_batch, { event: :success }) if !discarded_at && on_success.present?
            on_finish.constantize.set(priority: callback_priority, queue: callback_queue_name).perform_later(to_batch, { event: :finish }) if on_finish.present?
          end
        end
      end
    end

    class PropertySerializer
      def self.dump(value)
        ActiveJob::Arguments.serialize([value]).first
      end

      def self.load(value)
        ActiveJob::Arguments.deserialize([value]).first
      end
    end

    if Rails.gem_version < Gem::Version.new('6.1.0.alpha')
      # serialize does not yet take a default value, must set via Attributes API
      attribute :serialized_properties, :json, default: -> { {} }
      serialize :serialized_properties, PropertySerializer
    elsif Rails.gem_version < Gem::Version.new('7.1.0.alpha')
      serialize :serialized_properties, PropertySerializer, default: -> { {} }
    else
      serialize :serialized_properties, coder: PropertySerializer, default: -> { {} }
    end
    alias_attribute :properties, :serialized_properties

    def properties=(value)
      raise ArgumentError, "Properties must be a Hash" unless value.is_a?(Hash)

      self.serialized_properties = value
    end

    private

    def take_advisory_lock(value, &block)
      if value
        with_advisory_lock(function: "pg_advisory_lock", &block)
      else
        yield
      end
    end
  end
end

app/controllers/good_job/application_controller.rb
# frozen_string_literal: true

module GoodJob
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    around_action :use_good_job_locale

    content_security_policy do |policy|
      policy.default_src(:none) if policy.default_src(*policy.default_src).blank?
      policy.connect_src(:self) if policy.connect_src(*policy.connect_src).blank?
      policy.base_uri(:none) if policy.base_uri(*policy.base_uri).blank?
      policy.font_src(:self) if policy.font_src(*policy.font_src).blank?
      policy.img_src(:self, :data) if policy.img_src(*policy.img_src).blank?
      policy.object_src(:none) if policy.object_src(*policy.object_src).blank?
      policy.script_src(:self) if policy.script_src(*policy.script_src).blank?
      policy.style_src(:self) if policy.style_src(*policy.style_src).blank?
      policy.form_action(:self) if policy.form_action(*policy.form_action).blank?
      policy.frame_ancestors(:none) if policy.frame_ancestors(*policy.frame_ancestors).blank?
    end

    before_action do
      next if request.content_security_policy_nonce_generator

      request.content_security_policy_nonce_generator = ->(_request) { SecureRandom.base64(16) }
    end

    private

    def default_url_options(options = {})
      { locale: I18n.locale }.merge(options)
    end

    def use_good_job_locale(&action)
      @original_i18n_config = I18n.config
      I18n.config = ::GoodJob::I18nConfig.new
      I18n.with_locale(current_locale, &action)
    ensure
      I18n.config = @original_i18n_config
      @original_i18n_config = nil
    end

    def use_original_locale
      prev_config = I18n.config
      I18n.config = @original_i18n_config if @original_i18n_config
      yield
    ensure
      I18n.config = prev_config
    end

    def current_locale
      if request.GET['locale']
        request.GET['locale']
      elsif params[:locale]
        params[:locale]
      else
        I18n.default_locale
      end
    end

    ActiveSupport.run_load_hooks(:good_job_application_controller, self)
  end
end

app/controllers/good_job/batches_controller.rb
# frozen_string_literal: true

module GoodJob
  class BatchesController < GoodJob::ApplicationController
    def index
      @filter = BatchesFilter.new(params)
    end

    def show
      @batch = GoodJob::BatchRecord.find(params[:id])
    end
  end
end

app/views/good_job/jobs/_table.erb
<%= form_with(url: mass_update_jobs_path(filter.to_params), method: :put, local: true, data: { "checkbox-toggle": "job_ids" }) do |form| %>
  <div class="my-3 card" data-gj-poll-replace id="jobs-table">
    <div class="list-group list-group-flush text-nowrap table-jobs" role="table">
      <header class="list-group-item bg-body-tertiary">
        <div class="row small text-muted text-uppercase align-items-center">
          <div class="col-lg-4 d-flex gap-2 flex-wrap">
            <div class="form-check d-flex flex-row px-0 mb-0">
              <%= check_box_tag('toggle_job_ids', "1", false, data: { "checkbox-toggle-all": "job_ids" }) %>
              <%= label_tag('toggle_job_ids', t(".toggle_all_jobs"), class: "visually-hidden") %>
            </div>
            <%= form.button type: 'submit', name: 'mass_action', value: 'reschedule', class: 'ms-1 btn btn-sm btn-outline-secondary', title: t(".actions.reschedule_all"), data: { confirm: t(".actions.confirm_reschedule_all"), disable: true } do %>
              <span class="me-1"><%= render_icon "skip_forward" %></span> <%= t "good_job.actions.reschedule" %>
            <% end %>

            <%= form.button type: 'submit', name: 'mass_action', value: 'retry', class: 'btn btn-sm btn-outline-secondary', title: t(".actions.retry_all"), data: { confirm: t(".actions.confirm_retry_all"), disable: true } do %>
              <span class="me-1"><%= render_icon "arrow_clockwise" %></span> <%= t "good_job.actions.retry" %>
            <% end %>

            <div class="btn-group" role="group">
              <%= form.button type: 'submit', name: 'mass_action', value: 'discard', class: 'btn btn-sm btn-outline-secondary', title: t(".actions.discard_all"), data: { confirm: t(".actions.confirm_discard_all"), disable: true } do %>
                <span class="me-1"><%= render_icon "stop" %></span> <%= t "good_job.actions.discard" %>
              <% end %>
              <button id="destroy-dropdown-toggle" type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-expanded="false">
                <span class="visually-hidden"><%= t ".toggle_actions" %></span>
              </button>
              <ul class="dropdown-menu" aria-labelledby="destroy-dropdown-toggle">
                <li>
                  <%= form.button type: 'submit', name: 'mass_action', value: 'destroy', class: 'btn dropdown-item', title: t(".actions.destroy_all"), data: { confirm: t(".actions.confirm_destroy_all"), disable: true } do %>
                    <span class="me-1"><%= render_icon "trash" %></span> <%= t "good_job.actions.destroy" %>
                  <% end %>
                </li>
              </ul>
            </div>

          </div>
          <div class="d-none d-lg-block col-lg-1 text-lg-center"><%= t "good_job.models.job.queue" %></div>
          <div class="d-none d-lg-block col-lg-1 text-lg-end"><%= t "good_job.models.job.priority" %></div>
          <div class="d-none d-lg-block col-lg-1 text-lg-end"><%= t "good_job.models.job.attempts" %></div>
          <div class="col text-end">
            <%= tag.button type: "button", class: "btn btn-sm text-muted", role: "button",
              data: { bs_toggle: "collapse", bs_target: ".job-params" },
              aria: { expanded: false, controls: jobs.map { |job| "##{dom_id(job, 'params')}" }.join(" ") } do %>
              <%= render_icon "info" %>
              <span class="visually-hidden"><%= t "good_job.actions.inspect" %></span>
            <% end %>
          </div>
        </div>
      </header>
      <label role="row" class="list-group-item list-group-item-warning list-group-item-action py-2 d-none" data-checkbox-toggle-show="job_ids">
        <div class="row">
          <div class="col-auto">
            <%= check_box_tag "all_job_ids", 1, false, disabled: true, data: { "checkbox-toggle-show": "job_ids" } %>
          </div>
          <div class="col-auto">
            <%= t ".actions.apply_to_all", count: filter.filtered_count %>
          </div>
        </div>
      </label>

      <% if jobs.present? %>
        <% jobs.each do |job| %>
          <%= label_tag dom_id(job, :checkbox), id: dom_id(job), role: "row", class: "list-group-item list-group-item-action py-3" do %>
            <div class="row align-items-center">
              <div class="col-lg-4 d-flex">
                <%= check_box_tag 'job_ids[]', job.id, false, id: dom_id(job, :checkbox), data: { "checkbox-toggle-each": "job_ids" } %>
                <div class="ms-2">
                  <%= tag.code link_to(job.id, job_path(job), class: "small text-muted text-decoration-none") %>
                  <%= tag.h5 tag.code(link_to(job.display_name, job_path(job), class: "text-reset text-decoration-none")), class: "text-reset mb-0" %>
                  <% if job.error %>
                    <div class="mt-1 small">
                      <strong class="small text-danger"><%= t "good_job.shared.error" %>:</strong>
                      <code class="text-wrap text-break m-0 text-secondary-emphasis"><%= job.error %></code>
                    </div>
                  <% end %>
                </div>
              </div>
              <div class="col-4 col-lg-1 text-lg-center">
                <div class="d-lg-none small text-muted mt-1"><%= t "good_job.models.job.queue" %></div>
                <span class="badge bg-primary font-monospace"><%= job.queue_name %></span>
              </div>
              <div class="col-4 col-lg-1 text-lg-end">
                <div class="d-lg-none small text-muted mt-1"><%= t "good_job.models.job.priority" %></div>
                <%= job.priority %>
              </div>
              <div class="col-4 col-lg-1 text-lg-end">
                <div class="d-lg-none small text-muted mt-1"><%= t "good_job.models.job.attempts" %></div>
                <% if job.executions_count > 0 && job.status != :succeeded %>
                  <%= tag.span job.executions_count, class: "badge rounded-pill bg-danger",
                    data: {
                      bs_toggle: "popover",
                      bs_trigger: "hover focus click",
                      bs_placement: "bottom",
                      bs_content: job.display_error,
                    }
                  %>
                <% else %>
                  <span class="badge bg-secondary rounded-pill"><%= job.executions_count %></span>
                <% end %>
              </div>
              <div class="mt-3 mt-lg-0 col">
                <div class="d-flex gap-3 align-items-start justify-content-end">
                  <%= tag.span relative_time(job.last_status_at), class: "small mt-1" %>
                  <div>
                    <%= status_badge job.status %>
                    <% if job.status == :discarded && job.class.error_event_migrated? && job.error_event %>
                      <div class="text-black text-center">
                        <small><%= t(job.error_event, scope: 'good_job.error_event') %></small>
                      </div>
                    <% end %>
                  </div>

                  <div class="dropdown float-end">
                    <button class="d-flex align-items-center btn btn-sm" type="button" id="<%= dom_id(job, :actions) %>" data-bs-toggle="dropdown" aria-expanded="false">
                      <%= render_icon "dots" %>
                      <span class="visually-hidden"><%= t ".actions.title" %></span>
                    </button>
                    <ul class="dropdown-menu shadow" aria-labelledby="<%= dom_id(job, :actions) %>">
                      <li>
                        <% job_reschedulable = job.status.in? [:scheduled, :retried, :queued] %>
                        <%= link_to reschedule_job_path(job.id), method: :put, class: "dropdown-item #{'disabled' unless job_reschedulable}", title: t("good_job.jobs.actions.reschedule"), data: { confirm: t("good_job.jobs.actions.confirm_reschedule"), disable: true } do %>
                          <%= render_icon "skip_forward" %>
                          <%= t "good_job.actions.reschedule" %>
                        <% end %>
                      </li>
                      <li>
                        <% job_discardable = job.status.in? [:scheduled, :retried, :queued] %>
                        <%= link_to discard_job_path(job.id), method: :put, class: "dropdown-item #{'disabled' unless job_discardable}", title: t("good_job.jobs.actions.discard"), data: { confirm: t("good_job.jobs.actions.confirm_discard"), disable: true } do %>
                          <%= render_icon "stop" %>
                          <%= t "good_job.actions.discard" %>
                        <% end %>
                      </li>
                      <li>
                        <% job_force_discardable = job.status.in? [:running] %>
                        <%= link_to force_discard_job_path(job.id), method: :put, class: "dropdown-item #{'disabled' unless job_force_discardable}", title: t("good_job.jobs.actions.force_discard"), data: { confirm: t("good_job.jobs.actions.confirm_force_discard"), disable: true } do %>
                          <%= render_icon "eject" %>
                          <%= t "good_job.actions.force_discard" %>
                        <% end %>
                      </li>
                      <li>
                        <%= link_to retry_job_path(job.id), method: :put, class: "dropdown-item #{'disabled' unless job.status == :discarded}", title: t("good_job.jobs.actions.retry"), data: { confirm: t("good_job.jobs.actions.confirm_retry"), disable: true } do %>
                          <%= render_icon "arrow_clockwise" %>
                          <%= t "good_job.actions.retry" %>
                        <% end %>
                      </li>
                      <li>
                        <%= link_to job_path(job.id), method: :delete, class: "dropdown-item #{'disabled' unless job.status.in? [:discarded, :succeeded]}", title: t("good_job.jobs.actions.destroy"), data: { confirm: t("good_job.jobs.actions.confirm_destroy"), disable: true } do %>
                          <%= render_icon "trash" %>
                          <%= t "good_job.actions.destroy" %>
                        <% end %>
                      </li>

                      <li>
                        <%= link_to "##{dom_id(job, 'params')}",
                          class: "dropdown-item",
                          data: { bs_toggle: "collapse" },
                          aria: { expanded: false, controls: dom_id(job, "params") } do %>
                          <%= render_icon "info" %>
                          <%= t "good_job.actions.inspect" %>
                        <% end %>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
          <%= tag.div id: dom_id(job, "params"), class: "job-params list-group-item collapse small bg-dark text-light" do %>
            <%= tag.pre JSON.pretty_generate(job.display_serialized_params) %>
          <% end %>
        <% end %>
      <% else %>
        <div class="list-group-item py-4 text-center text-muted">
          <%= t ".no_jobs_found" %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/good_job/jobs/index.html.erb
<%= render 'good_job/shared/filter', title: t("good_job.shared.navbar.jobs"), filter: @filter %>
<%= render 'good_job/shared/chart', chart_data: GoodJob::ScheduledByQueueChart.new(@filter).data %>

<div data-live-poll-region="jobs-table">
  <%= render 'good_job/jobs/table', jobs: @filter.records, filter: @filter %>
  <% if @filter.records.present? %>
    <nav aria-label="<%= t ".job_pagination" %>" class="mt-3">
      <ul class="pagination">
        <li class="page-item">
          <%= link_to(@filter.to_params(after_scheduled_at: (@filter.last.scheduled_at || @filter.last.created_at), after_id: @filter.last.id), class: "page-link") do %>
            <%= t ".older_jobs" %> <span aria-hidden="true">&raquo;</span>
          <% end %>
        </li>
      </ul>
    </nav>
  <% end %>
</div>